language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-gelf.gemspec
- gem install sensu-plugins-gelf-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: c/bAcYtiAbyLRtCPRWaGJLELss9OfXzcHQjdtohpjJg47ZscvEt3Z5qbJ67WPED8HYALxFM9JiOM4GjryZh0BrI4Q3L+5y9bKY5UUrBZKcfAWWclBTcARmzkt+uANfZs1aeZEcPYnW93gtmptKDdMy7jSWQpbn62lHtNeRusHpw=
  gem: sensu-plugins-gelf
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-gelf
